"""Post

Revision ID: 84876b58d9b1
Revises: ce6da540b948
Create Date: 2024-10-31 18:44:30.186653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84876b58d9b1'
down_revision = 'ce6da540b948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
