"""going  back to prev

Revision ID: df203ba6c3c4
Revises: 36d76571b992
Create Date: 2024-10-27 12:08:10.530728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df203ba6c3c4'
down_revision = '36d76571b992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=120), nullable=True))
        batch_op.drop_column('clean_package')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_package', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
